server:
  port: 443
  ssl:
    certificate: cert.pem
    certificate-private-key: key.pem
  address: 0.0.0.0


spring:
  application:
    name: hycord
  mvc:
    static-path-pattern: /static/**

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html